config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#landing"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get "/home", to: "pages#home"
  get "/dashboard", to: "pages#dashboard"

  resources :profiles, except: [:index, :destroy]
  resources :recipe_ingredients
  resources :recipes, only: [:index, :show] do
    resources :favorites, only: [:create, :destroy]
    resources :recap_recipes, only: [:create]
  end
  resources :recap_recipes, only: [:index, :destroy]
  resources :favorites, only: [:index]
  resources :chats do
    resources :messages
  end
  resources :ingredients_lists, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  acts_as_chat
  has_many :messages, dependent: :destroy
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validates :recipe_id, uniqueness: { scope: :user_id, message: "est déjà en favoris" }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :recipes, through: :recipe_ingredients
end

app/models/ingredients_list.rb
class IngredientsList < ApplicationRecord
  belongs_to :recap_recipe
  
end

app/models/message.rb
class Message < ApplicationRecord
  acts_as_message
  belongs_to :chat
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/recap_recipe.rb
class RecapRecipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :user_id, presence: true
  validates :recipe_id, presence: true
  validates :recipe_id, uniqueness: {
    scope: :user_id,
    message: "est déjà dans votre sélection"
  }

  has_one :ingredients_list, dependent: :destroy
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # has_neighbors :embedding
  # after_create :set_embedding
  has_many :recipe_ingredients
  has_many :favorites
  has_many :ingredients, through: :recipe_ingredients
  has_many_attached :photos


  has_many :recap_recipes, dependent: :destroy

  private

   def set_embedding
    embedding = RubyLLM.embed("Recipe: #{name}. Description: #{description}. Price: #{price}. Time: #{time}. Calories: #{calories}.")
    update(embedding: embedding.vectors)
  end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/tool_call.rb
class ToolCall < ApplicationRecord
  acts_as_tool_call

  belongs_to :message
end

app/models/user.rb
class User < ApplicationRecord
  after_create :create_default_chat
  has_one :profile
  has_many :favorites
  has_one :chat, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recap_recipes, dependent: :destroy
  has_many :selected_recipes, through: :recap_recipes, source: :recipe

  private

  def create_default_chat
    Chat.create!(
      user: self,
      title: "Vide ton frigo avec TupChef",
      model_id: "gpt-4.1-nano"
    )
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  def show
    @chat = Chat.find(params[:id])
    @message = Message.new
  end

  def new
    @chat = Chat.new
  end

  def create
    @chat = Chat.new(title: "Vide ton frigo avec TupLunch", model_id: "gpt-4.1-nano")
    @chat.user = current_user
    if @chat.save
      redirect_to chat_message_path(@chat)
    else
      redirect_to root_path, alert: "Impossible de créer le chat"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_markdown(text)
    Kramdown::Document.new(text, input: 'GFM', syntax_highlighter: "rouge").to_html
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="footer-nav">
    <%= link_to home_path, class: "footer-link" do %>
      <%= image_tag "home.png", alt: "Home", class: "footer-icon" %>
    <% end %>
    <%= link_to ingredients_lists_path, class: "footer-link" do %>
      <%= image_tag "list.png", alt: "Liste", class: "footer-icon" %>
    <% end %>
    <%= link_to recipes_path, class: "footer-link" do %>
      <%= image_tag "cards.png", alt: "Recipes", class: "footer-icon" %>
    <% end %>
    <%= link_to chat_path(current_user.chat), class: "footer-link" do %>
      <%= image_tag "chef.png", alt: "Checklist", class: "footer-icon" %>
    <% end %>
    <%= link_to dashboard_path, class: "footer-link" do %>
      <%= image_tag "profile.png", alt: "Chef", class: "footer-icon" %>
    <% end %>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TupLunch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Modak&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <% unless (controller_name == "pages" && action_name == "landing") ||
                (controller_name == "recipes" && action_name == "show")
        %>
    <%= render "shared/navbar" %>
  <% end %>
  <div id="body-home"><%= yield %></div>
  <% if user_signed_in? %>
    <% unless (controller_name == "pages" && action_name == "landing") ||
              (controller_name == "recap_recipes" && action_name == "index") ||
              (controller_name == "recipes" && action_name == "show") ||
              controller_name == "devise"
      %>
    <%= render "layouts/footer" %>
  <% end %>
<% end %>
</body>
</html>

app/views/pages/dashboard.html.erb
<H2>My account</H2>
<div class="col-md-4 mb-3">
  <div class="card shadow-sm">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h5 class="mb-0"><%= @profile.name %></h5>
      <%= link_to "⚙️", edit_profile_path(@profile), class: "btn btn-outline-secondary btn-sm" %>
    </div>
    <div class="card-body">
      <p class="card-text mb-1"><strong>Préférences :</strong></p>
      <p class="card-text text-muted"><%= @profile.food_preferences %></p>
    </div>
  </div>
</div>
<H2>My recipes(nombre de recettes)</H2>
<div class="container mt-4">
  <div class="row">
    <% @recap_recipes.each do |recipe| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= recipe.recipe.name %></h5>
            <p class="card-text"><%= recipe.recipe.description %></p>
            <%= link_to "show this recipe", recipe_path(recipe.recipe_id)%>
            <%= link_to "🚮", recap_recipe_path(recipe), data: { turbo_method: :delete, confirm: "Avez-vous effectué cette recette ?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<H2>My favorites</H2>
<div class="container mt-4">
  <div class="row">
    <% @favorites.each do |favorite| %>
      <div class="col-md-4 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= favorite.recipe.name %></h5>
            <p class="card-text"><%= favorite.recipe.description %></p>
            <%= link_to "show this recipe", recipe_path(favorite.recipe_id)%>
            <%= link_to "🚮", recipe_favorite_path(favorite.recipe_id, favorite.id), data: { turbo_method: :delete, confirm: "Voulez-vous vraiment retirer cette recette de vos favoris ?"}%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<main class="homepage" style="background:#00524F; min-height:100vh; padding:16px;">
  <!-- ===== HERO ===== -->
  <section class="hero">
    <!-- Image d’arrière-plan -->
    <%= image_tag "plat-home.jpg", alt: "Assiette de sushi", loading: "eager" %>
    <div class="hero-content">
      <h2>Générez vos repas et optimisez votre budget</h2>
      <%= link_to "Let’s goooo", recipes_path, class: "cta-btn" %>
    </div>
  </section>

  <section class="recipes-section">
    <h3>Les recettes du moment</h3>
    <div class="recipes-carousel">
      <% @recipes.each do |recipe| %>

        <article class="recipe-card">
          <%= link_to recipe_path(recipe), class: "recipe-link" do  %>
            <div class="image-wrapper">
              <% recipe.photos.each do |photo| %>
                <%= cl_image_tag(photo.key)%>
          <% end  %>
              <% end %>
            </div>
            <h4><%= recipe.name %></h4>
            <div class="meta">Prix</div>
            <div class="time"><%= "#{number_to_currency(recipe.price, unit: "€")}" %></div>
          <%= link_to "🤍", recipe_favorites_path(recipe),
                data: { turbo_method: :post },
                class: "fav-btn" %>
        </article>
      <% end %>
    </div>
  </section>
</main>

app/views/pages/landing.html.erb
<div class="landing-hero">
  <!-- Badge top -->
  <div class="landing-badge">
    <span class="landing-star">★</span>
    <span>500+ Recettes</span>
  </div>
  <%= image_tag "decor.svg", class: "landing-decor", alt: "Decor" %>
  <%= image_tag "ligne.svg", class:"landing-ligne", alt: "ligne" %>
  <div class="landing-content">
    <div class="mb-3">
      <h1 class="landing-title">TupLunch</h1>
    </div>
    <p class="landing-subtitle mb-3">Rendez vos repas plus fun</p>
    <%= link_to "Let's cook", home_path, class: "btn-cta" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar shadow-md">
  <%# <div class="nav-left flex items-center"> %>
    <%# <%= image_tag "logo.png", alt: "Logo TupLunch", class: "logo" %>
  <%# </div> %>

  <div class="title-navbar">
    <span class="text">TupLunch</span>
  </div>
</nav>